"""
Run a LEAN backtest by writing generated code to a project directory
and invoking the Lean CLI via subprocess.
"""
from __future__ import annotations
import json
import os
import subprocess
import glob
from pathlib import Path
from typing import Dict, Optional

LEAN_ROOT = Path(__file__).resolve().parent.parent.parent / "lean"
PROJECT_NAME = "BlocklyRun"
BACKTEST_TIMEOUT = 120  # seconds


class LeanRunnerError(Exception):
    """Raised when the Lean CLI fails or times out."""
    pass


def run_lean_backtest(generated_code: str) -> Dict[str, Path]:
    """
    Write generated_code to a LEAN project and run `lean backtest`.

    Returns dict with keys:
        - 'summary': Path to the *-summary.json file
        - 'order_events': Path to the *-order-events.json file
        - 'log': Path to the log.txt file
        - 'result_dir': Path to the backtest output directory
    """
    project_dir = LEAN_ROOT / PROJECT_NAME
    project_dir.mkdir(parents=True, exist_ok=True)

    main_py = project_dir / "main.py"
    main_py.write_text(generated_code, encoding="utf-8")

    config_file = project_dir / "config.json"
    config_file.write_text(json.dumps({
        "algorithm-language": "Python",
        "parameters": {},
        "description": "Generated by Blockly Strategy Builder",
    }, indent=4), encoding="utf-8")

    try:
        result = subprocess.run(
            ["lean", "backtest", PROJECT_NAME],
            cwd=str(LEAN_ROOT),
            capture_output=True,
            text=True,
            timeout=BACKTEST_TIMEOUT,
        )
    except FileNotFoundError:
        raise LeanRunnerError(
            "Lean CLI not found. Make sure 'lean' is installed and on your PATH. "
            "Install with: pip install lean"
        )
    except subprocess.TimeoutExpired:
        raise LeanRunnerError(
            f"Backtest timed out after {BACKTEST_TIMEOUT} seconds. "
            "Try a shorter date range or lower resolution."
        )

    if result.returncode != 0:
        stderr = result.stderr.strip()
        stdout = result.stdout.strip()
        msg = stderr or stdout or "Unknown error"
        if "docker" in msg.lower():
            raise LeanRunnerError(
                "Docker does not appear to be running. "
                "LEAN requires Docker — please start Docker Desktop and try again."
            )
        # LEAN often exits non-zero even on success (assembly warnings, etc.)
        # Check if results were actually produced before treating as failure
        try:
            return _find_latest_results(project_dir / "backtests")
        except LeanRunnerError:
            raise LeanRunnerError(f"Lean backtest failed: {msg[:1000]}")

    return _find_latest_results(project_dir / "backtests")


def _find_latest_results(backtests_dir: Path) -> Dict[str, Path]:
    """Find the most recent backtest output directory and its key files."""
    if not backtests_dir.exists():
        raise LeanRunnerError("No backtest output directory found — LEAN may not have run correctly")

    run_dirs = sorted(backtests_dir.iterdir(), key=os.path.getmtime, reverse=True)
    run_dirs = [d for d in run_dirs if d.is_dir()]

    if not run_dirs:
        raise LeanRunnerError("No backtest results found in output directory")

    latest = run_dirs[0]

    summary_files = glob.glob(str(latest / "*-summary.json"))
    order_files = glob.glob(str(latest / "*-order-events.json"))
    log_file = latest / "log.txt"

    if not summary_files:
        log_content = ""
        if log_file.exists():
            log_content = log_file.read_text(encoding="utf-8", errors="replace")[-2000:]
        raise LeanRunnerError(
            f"Backtest completed but no summary file was produced. "
            f"Check the log for errors:\n{log_content}"
        )

    return {
        "summary": Path(summary_files[0]),
        "order_events": Path(order_files[0]) if order_files else None,
        "log": log_file if log_file.exists() else None,
        "result_dir": latest,
    }
